# Generated by Django 3.0.2 on 2020-02-01 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='activation_key',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='key_expires',
        ),
        migrations.AddField(
            model_name='unverifyuser',
            name='isCreate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unverifyuser',
            name='school',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='schools.School'),
        ),
        migrations.AlterField(
            model_name='unverifyuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='unverifyuser',
            name='token',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
