# Generated by Django 3.0.2 on 2020-02-01 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('users', '0002_auto_20200201_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unverifyuser',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schools.School'),
        ),
    ]
