# Generated by Django 3.0.2 on 2020-01-31 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0003_unverifyuser_userdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnverifyUser',
        ),
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
