# Generated by Django 3.0.2 on 2020-02-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0005_auto_20200201_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
    ]
